# List of all snaphots/configs
# 
# F2 - to append current snapshot (only fractl-anim application)
# F3 - to restore (consecutive) ones, starting from latest
# One can also try to edit fields, especially description,
#     or copy/paste whole [[config]] section  
#------------------------------------------------------------------------


#-------------------------------------------------------------

[[config]]

  description = "Dark Green" 
  time-date = "Thursday 22-May-25  15:51:42"

  [config.primary]  # Primary element location/size
    x = 30
    y = 530
    dx = 1000
    dy = -80

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 43, green = 160, blue = 9}
        end = {red = 156, green = 162, blue = 143}
    [[config.colors.level]]
      begin = {red = 156, green = 12, blue = 144}
        end = {red = 60, green = 67, blue = 36}
    [[config.colors.level]]
      begin = {red = 18, green = 18, blue = 106}
        end = {red = 142, green = 31, blue = 70}
    [[config.colors.level]]
      begin = {red = 54, green = 92, blue = 136}
        end = {red = 112, green = 150, blue = 156}
    [[config.colors.level]]
      begin = {red = 51, green = 96, blue = 156}
        end = {red = 112, green = 94, blue = 156}
    [[config.colors.level]]
      begin = {red = 27, green = 104, blue = 8}
        end = {red = 26, green = 3, blue = 52}
    [[config.colors.level]]
      begin = {red = 120, green = 148, blue = 45}
        end = {red = 25, green = 22, blue = 39}
    [[config.colors.level]]
      begin = {red = 43, green = 160, blue = 9}
        end = {red = 156, green = 162, blue = 143}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.222, angle = 750, scale = 0.38},
      {reposition = 0.445, angle = 686, scale = 0.3225},
      {reposition = 0.634, angle = 625, scale = 0.265},
      {reposition = 0.790, angle = 561, scale = 0.2075},
      {reposition = 0.912, angle = 500, scale = 0.15},
     ]


#-------------------------------------------------------------

[[config]]

  description = "Rotated - Orange" 
  time-date = "Thursday 29-May-25  15:51:42"

  [config.primary]  # Primary element location/size
    x = 30
    y = 830
    dx = 700
    dy = -700

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 237, green = 117, blue = 246}
        end = {red = 171, green = 81, blue = 16}
    [[config.colors.level]]
      begin = {red = 109, green = 189, blue = 52}
        end = {red = 146, green = 38, blue = 196}
    [[config.colors.level]]
      begin = {red = 253, green = 40, blue = 45}
        end = {red = 68, green = 43, blue = 14}
    [[config.colors.level]]
      begin = {red = 225, green = 218, blue = 220}
        end = {red = 181, green = 3, blue = 38}
    [[config.colors.level]]
      begin = {red = 145, green = 83, blue = 86}
        end = {red = 6, green = 191, blue = 1}
    [[config.colors.level]]
      begin = {red = 251, green = 54, blue = 47}
        end = {red = 77, green = 70, blue = 29}
    [[config.colors.level]]
      begin = {red = 138, green = 122, blue = 200}
        end = {red = 48, green = 191, blue = 182}
    [[config.colors.level]]
      begin = {red = 88, green = 236, blue = 73}
        end = {red = 4, green = 122, blue = 71}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.222, angle = 750, scale = 0.38},
      {reposition = 0.445, angle = 686, scale = 0.3225},
      {reposition = 0.634, angle = 625, scale = 0.265},
      {reposition = 0.790, angle = 561, scale = 0.2075},
      {reposition = 0.912, angle = 500, scale = 0.15},
     ]

#-------------------------------------------------------------

[[config]]

  description = "Wool 2 (can be slow)" 
  time-date = "Thursday 29-May-25  11:55:10"

  [config.primary]  # Primary element location/size
    x = 79
    y = 521
    dx = 872
    dy = -69

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 17, green = 190, blue = 19}
        end = {red = 29, green = 241, blue = 234}
    [[config.colors.level]]
      begin = {red = 4, green = 238, blue = 18}
        end = {red = 8, green = 14, blue = 167}
    [[config.colors.level]]
      begin = {red = 246, green = 207, blue = 51}
        end = {red = 164, green = 57, blue = 250}
    [[config.colors.level]]
      begin = {red = 205, green = 44, blue = 249}
        end = {red = 243, green = 40, blue = 55}
    [[config.colors.level]]
      begin = {red = 24, green = 81, blue = 65}
        end = {red = 210, green = 4, blue = 161}
    [[config.colors.level]]
      begin = {red = 26, green = 75, blue = 63}
        end = {red = 64, green = 46, blue = 156}
    [[config.colors.level]]
      begin = {red = 239, green = 91, blue = 18}
        end = {red = 190, green = 66, blue = 240}
    [[config.colors.level]]
      begin = {red = 217, green = 247, blue = 52}
        end = {red = 180, green = 221, blue = 173}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.237, angle = 255, scale = 0.532},
      {reposition = 0.475, angle = 233, scale = 0.4365},
      {reposition = 0.670, angle = 211, scale = 0.341},
      {reposition = 0.823, angle = 190, scale = 0.2455},
      {reposition = 0.932, angle = 168, scale = 0.15},
     ]

#-------------------------------------------------------------

[[config]]

  description = "Cotton Wool (can be slow)" 
  time-date = "Wednesday 28-May-25  15:45:52"

  [config.primary]  # Primary element location/size
    x = 79
    y = 521
    dx = 872
    dy = -69

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 204, green = 0, blue = 0}
        end = {red = 160, green = 160, blue = 0}
    [[config.colors.level]]
      begin = {red = 160, green = 160, blue = 0}
        end = {red = 0, green = 204, blue = 0}
    [[config.colors.level]]
      begin = {red = 0, green = 204, blue = 0}
        end = {red = 0, green = 0, blue = 204}
    [[config.colors.level]]
      begin = {red = 0, green = 0, blue = 204}
        end = {red = 120, green = 0, blue = 160}
    [[config.colors.level]]
      begin = {red = 204, green = 0, blue = 0}
        end = {red = 160, green = 160, blue = 0}
    [[config.colors.level]]
      begin = {red = 160, green = 160, blue = 0}
        end = {red = 0, green = 204, blue = 0}
    [[config.colors.level]]
      begin = {red = 0, green = 0, blue = 204}
        end = {red = 120, green = 0, blue = 160}
    [[config.colors.level]]
      begin = {red = 204, green = 0, blue = 0}
        end = {red = 160, green = 160, blue = 0}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.237, angle = 440, scale = 0.532},
      {reposition = 0.475, angle = 403, scale = 0.4365},
      {reposition = 0.670, angle = 366, scale = 0.341},
      {reposition = 0.823, angle = 329, scale = 0.2455},
      {reposition = 0.932, angle = 292, scale = 0.15},
     ]



#-------------------------------------------------------------

[[config]]

  description = "Rainbow (default)" 
  time-date = "Sunday 25-May-25  16:58:31"

  [config.primary]  # Primary element location/size
    x = 30
    y = 530
    dx = 1000
    dy = -80
    width = 20

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 163, green = 0, blue = 0}     # Red
        end = {red = 128, green = 128, blue = 0}   # yellow
    [[config.colors.level]]
      begin = {red = 128, green = 128, blue = 0}   # yellow
        end = {red = 0, green = 163, blue = 0}     # green
    [[config.colors.level]]
      begin = {red = 0, green = 163, blue = 0}     # green
        end = {red = 0, green = 0, blue = 163}     # Blue
    [[config.colors.level]]
      begin = {red = 0, green = 0, blue = 163}     # Blue
        end = {red = 150, green = 0, blue = 128}   # Magenta
    [[config.colors.level]]
      begin = {red = 163, green = 0, blue = 0}     # Red
        end = {red = 128, green = 128, blue = 0}   # yellow
    [[config.colors.level]]
      begin = {red = 128, green = 128, blue = 0}   # yellow
        end = {red = 0, green = 163, blue = 0}     # green
    [[config.colors.level]]
      begin = {red = 0, green = 0, blue = 163}     # Blue
        end = {red = 150, green = 0, blue = 128}   # Magenta
    [[config.colors.level]]
      begin = {red = 163, green = 0, blue = 0}     # Red
        end = {red = 128, green = 128, blue = 0}   # yellow

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.222, angle = 750, scale = 0.38},
      {reposition = 0.445, angle = 686, scale = 0.3225},
      {reposition = 0.634, angle = 625, scale = 0.265},
      {reposition = 0.790, angle = 561, scale = 0.2075},
      {reposition = 0.912, angle = 500, scale = 0.15},
     ]

#-------------------------------------------------------------

[[config]]

  description = "Sharp colors - orange" 
  time-date = "Tuesday 27-May-25  13:03:00"

  [config.primary]  # Primary element location/size
    x = 30
    y = 530
    dx = 1000
    dy = -80

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 237, green = 117, blue = 246}
        end = {red = 171, green = 81, blue = 16}
    [[config.colors.level]]
      begin = {red = 109, green = 189, blue = 52}
        end = {red = 146, green = 38, blue = 196}
    [[config.colors.level]]
      begin = {red = 253, green = 40, blue = 45}
        end = {red = 68, green = 43, blue = 14}
    [[config.colors.level]]
      begin = {red = 225, green = 218, blue = 220}
        end = {red = 181, green = 3, blue = 38}
    [[config.colors.level]]
      begin = {red = 145, green = 83, blue = 86}
        end = {red = 6, green = 191, blue = 1}
    [[config.colors.level]]
      begin = {red = 251, green = 54, blue = 47}
        end = {red = 77, green = 70, blue = 29}
    [[config.colors.level]]
      begin = {red = 138, green = 122, blue = 200}
        end = {red = 48, green = 191, blue = 182}
    [[config.colors.level]]
      begin = {red = 88, green = 236, blue = 73}
        end = {red = 4, green = 122, blue = 71}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.222, angle = 750, scale = 0.38},
      {reposition = 0.445, angle = 686, scale = 0.3225},
      {reposition = 0.634, angle = 625, scale = 0.265},
      {reposition = 0.790, angle = 561, scale = 0.2075},
      {reposition = 0.912, angle = 500, scale = 0.15},
     ]

#-------------------------------------------------------------

[[config]]

  description = "Light - more dense" 
  time-date = "Saturday 31-May-25  10:17:37"

  [config.primary]  # Primary element location/size
    x = 58
    y = 512
    dx = 945
    dy = -75

  [config.colors]
  # Colors of consecutive levels, begin to end stem

    [[config.colors.level]]
      begin = {red = 195, green = 121, blue = 191}
        end = {red = 141, green = 24, blue = 105}
    [[config.colors.level]]
      begin = {red = 65, green = 199, blue = 28}
        end = {red = 28, green = 180, blue = 134}
    [[config.colors.level]]
      begin = {red = 181, green = 19, blue = 44}
        end = {red = 63, green = 107, blue = 130}
    [[config.colors.level]]
      begin = {red = 190, green = 162, blue = 96}
        end = {red = 196, green = 141, blue = 109}
    [[config.colors.level]]
      begin = {red = 180, green = 63, blue = 107}
        end = {red = 134, green = 49, blue = 154}
    [[config.colors.level]]
      begin = {red = 52, green = 138, blue = 140}
        end = {red = 76, green = 141, blue = 131}
    [[config.colors.level]]
      begin = {red = 173, green = 169, blue = 170}
        end = {red = 150, green = 202, blue = 32}
    [[config.colors.level]]
      begin = {red = 169, green = 144, blue = 163}
        end = {red = 175, green = 70, blue = 140}

  [config.transform]
    # consecutive elements/branches
    element = [
      {reposition = 0.234, angle = 660, scale = 0.422851},
      {reposition = 0.468, angle = 605, scale = 0.349669},
      {reposition = 0.662, angle = 550, scale = 0.276488},
      {reposition = 0.815, angle = 495, scale = 0.203306},
      {reposition = 0.927, angle = 440, scale = 0.130125},
     ]

